### ISSUE TITLE
Plugin does not start

### ISSUE THREAD

**Issue by tkurki** [joabakk/signalk-tides-api#12]
After installation the plugin config does not load:
```
TypeError: Cannot read property 'map' of undefined
    at Request.request [as _callback] (/Users/tjk/.signalk/node_modules/signalk-tides-api/calcs/noaa.js:41:43)
    at Request.self.callback (/Users/tjk/.signalk/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/Users/tjk/.signalk/node_modules/request/request.js:1161:10)
 ```

**Comment by joabakk** [comment]
Noaa has changed their API and now I cannot find a way to look for stations. Disabling NOAA for the time being

**Comment by joabakk** [comment]
Updated to the newest API. Thanks for spotting
